### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "first_name": "Mia2",
    "last_name": "Miazera2",
    "nickname": "Mia2",
    "partnership": "1",
    "password": "mia123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "nickname": "Mia",
    "password": "asdfg123"
}
//asdfg123

### 3) Cancel partnership
DELETE  http://localhost:3003/users/cancelMembershipAna
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0ZjMxZWZhLWMzNGItNDk0ZS05ODFiLTdlZmE1M2IxMDI0YyIsImlhdCI6MTY2NjgyNDkxMiwiZXhwIjoxNjY2OTExMzEyfQ.0JvTPdN4ckjiRoIfxgFu495W__w4Q9A2Cjiua8zqlA4

### 4) Get all members
GET http://localhost:3003/users/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMyIsImlhdCI6MTY2NjgyNTA1OCwiZXhwIjoxNjY2OTExNDU4fQ.nxT_Ei2pwWCYTTxAFG6EpLxfAqMBbEhmLjtjLv5J6CA

### 5) Get availables shares
GET http://localhost:3003/users/shares
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMyIsImlhdCI6MTY2NjgxMDQ0OSwiZXhwIjoxNjY2ODk2ODQ5fQ.AHO67EHEEHwwoG81Y7JnltTx4xIOY2GpWdvwHAV_RYw
