### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "first_name": "Mia4",
    "last_name": "Miazera4",
    "nickname": "Mia4",
    "partnership": 99,
    "password": "mia123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "nickname": "Mia",
    "password": "asdfg123"
}

### 3) Cancel partnership
DELETE  http://localhost:3003/users/cancelMembership
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyZWI1YWQyLWU3NjYtNDcwNi05N2M0LWQ5NzhhMmRiNDc0NCIsImlhdCI6MTY2NjY5OTAxOSwiZXhwIjoxNjY2Nzg1NDE5fQ.H5Lw0L_khEBuhwzdUMa3rh3I3snuMwk3Z31d7tJEWB0

{
    "nickname": "Mia4",
    "password": "mia123"
}
###

GET http://localhost:3003/users/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NzEzYTcwLWE3OWMtNDBlMy1hYjZjLTU5ZmU2YWQxNmEzMSIsImlhdCI6MTY2NjY5ODI4OSwiZXhwIjoxNjY2Nzg0Njg5fQ.-Z8qwXYNWahY3OWoH1TOpOimXGfIu0gXL-Ext1OMjVE

############################################################################
### 5) Post tickets's book
POST http://localhost:3003/shows/bookingTicket/4d7a8934-23f3-4200-9d4e-041050bb6ce6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2OGRhMDU4LWE5OWUtNDc1Ny05MDZkLTI0ZWE0OTBkNDg4MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ2MzMxODgsImV4cCI6MTY2NDcxOTU4OH0.XLWPgGEkzH5uALWIBg8RO-a3rJ8d06XZ4aC6WN-U06A

### 6) Del tickets's book
DELETE http://localhost:3003/shows/delBooking/4d7a8934-23f3-4200-9d4e-041050bb6ce6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2OGRhMDU4LWE5OWUtNDc1Ny05MDZkLTI0ZWE0OTBkNDg4MiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ2MzMxODgsImV4cCI6MTY2NDcxOTU4OH0.XLWPgGEkzH5uALWIBg8RO-a3rJ8d06XZ4aC6WN-U06A

### 7) Coverage = 51%
//Ok

### 8) Coverage = 80%
//Ok
