### Endpoint de teste
GET http://localhost:3003/ping

### Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "first_name": "Mia2",
    "last_name": "Miazera2",
    "nickname": "Mia2",
    "partnership": "1",
    "password": "mia123"
}

### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "nickname": "Mia",
    "password": "asdfg123"
}
//asdfg123

### Cancel partnership
DELETE  http://localhost:3003/users/cancelMembershipAna
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0ZjMxZWZhLWMzNGItNDk0ZS05ODFiLTdlZmE1M2IxMDI0YyIsImlhdCI6MTY2NjgyNDkxMiwiZXhwIjoxNjY2OTExMzEyfQ.0JvTPdN4ckjiRoIfxgFu495W__w4Q9A2Cjiua8zqlA4

### Get all members
GET http://localhost:3003/users/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMyIsImlhdCI6MTY2NzY4NDkzOCwiZXhwIjoxNjY3NzcxMzM4fQ.6MwPm7sUbkpOzDJaHLdEB3gmCty8wf4jUXWtI6BsvPk

### Get availables shares
GET http://localhost:3003/users/shares
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMyIsImlhdCI6MTY2NzY4NDkzOCwiZXhwIjoxNjY3NzcxMzM4fQ.6MwPm7sUbkpOzDJaHLdEB3gmCty8wf4jUXWtI6BsvPk

### Update user's partnership
PUT http://localhost:3003/users/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMyIsImlhdCI6MTY2NzY4NDkzOCwiZXhwIjoxNjY3NzcxMzM4fQ.6MwPm7sUbkpOzDJaHLdEB3gmCty8wf4jUXWtI6BsvPk

{
    "nickname": "Mia",
    "partnership": 13
}