CREATE TABLE User (
	id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

select * from User;

ALTER TABLE User ADD role VARCHAR(7) NOT NULL DEFAULT "normal";