### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Raul11",
    "email": "raul11@gmail.com",
    "password": "raul123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Post Show
POST http://localhost:3003/shows/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDQ4NDg0MSwiZXhwIjoxNjY0NTcxMjQxfQ.EYJMCAU7UyfJSOPDsqwRZP4-hxs9VYZ4gZriP2rkg18

{
    "band": "Teste2",
    "starts_at": "2022/12/06"
}

### 4) Gel All Shows with tickets
GET http://localhost:3003/shows/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDQ2MzA4OSwiZXhwIjoxNjY0NTQ5NDg5fQ.-dAOxjpzWrRdzYCX-PDf1c-uN41nJrBG5maWS2pqZ5A

### 5) Post tickets's book
POST http://localhost:3003/shows/bookingTicket
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmYzcwOTdlLTQ0YTMtNGQyOS04NTBmLTU3MTI2NGI1NGQ3YyIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ0ODU0NzgsImV4cCI6MTY2NDU3MTg3OH0.5yiXsH7erWb5Mwtgp5k-YSnyPhauElq9f0LnYc3CuM0

{
    "show_id": "4d7a8934-23f3-4200-9d4e-041050bb6ce6"
}
### 6) Del tickets's book
DELETE http://localhost:3003/shows/delBooking
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmYzcwOTdlLTQ0YTMtNGQyOS04NTBmLTU3MTI2NGI1NGQ3YyIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ0ODU0NzgsImV4cCI6MTY2NDU3MTg3OH0.5yiXsH7erWb5Mwtgp5k-YSnyPhauElq9f0LnYc3CuM0

{
    "show_id": "4d7a8934-23f3-4200-9d4e-041050bb6ce6"
}

### 7) Coverage = 51%

### 8) Coverage = 80%
